kelompok13/funeducare/aboutus/urls.py
from django.urls import path
from . import views

app_name = 'aboutus'
urlpatterns = [
    path('', views.aboutus_view, name='aboutus'),  
]

kelompok13/funeducare/contactus/urls.py
from django.urls import path
from . import views


app_name='contactus'

urlpatterns = [
    path('', views.contactus_view, name='contactus'),
]

kelompok13/funeducare/funeducare/urls.py
from django.contrib import admin
from django.urls import path, include
from aboutus import views
from contactus import views
from home import views
from payments import views
from pendaftaran import views
from profil import views
from programs import views
from users import views

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('contactus/', include('contactus.urls')),
    path('aboutus/', include('aboutus.urls')),
    path('programs/', include('programs.urls')),
    path('users/', include('users.urls')),
    
]

kelompok13/funeducare/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home_view, name='home'),
]

kelompok13/funeducare/payments/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

kelompok13/funeducare/pendaftaran/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

kelompok13/funeducare/profil/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

kelompok13/funeducare/programs/urls.py
from django.urls import path
from . import views

app_name = 'programs'

urlpatterns = [
    path('', views.programs, name='programs'),
]

kelompok13/funeducare/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
app_name = 'users'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.user_logout, name='logout'),
    path('login/', views.user_login, name='login'),
    path('profile/', views.profile_view, name='profile'),
    
]

kelompok13/funeducare/payments/models.py
from django.db import models

# Create your models here.

kelompok13/funeducare/profil/models.py
from django.db import models

# Create your models here.

kelompok13/funeducare/reports/models.py
from django.db import models

# Create your models here.

kelompok13/funeducare/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):


    def __str__(self):
        return self.username

kelompok13/funeducare/contactus/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100, required=True)
    email = forms.EmailField(label='Email', required=True)
    contact = forms.CharField(label='Contact Number', max_length=20, required=True)
    message = forms.CharField(label='Message', widget=forms.Textarea, required=True)

kelompok13/funeducare/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class SignupForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Masukkan Email Anda'})
    )
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Masukkan Password Anda'})
    )
    password2 = forms.CharField(
        label="Verifikasi Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Masukkan Ulang Password Anda'})
    )

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Masukkan Username Anda'}),
        }
        
class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

kelompok13/funeducare/aboutus/views.py
from django.shortcuts import render

# Create your views here.
def aboutus_view(request):
    return render(request, 'aboutus/aboutus.html')

kelompok13/funeducare/contactus/views.py
from django.shortcuts import render

# Create your views here.
def contactus_view(request):
    return render(request,'contactus/contactus.html')

kelompok13/funeducare/home/views.py
from django.shortcuts import render

# Create your views here.
def home_view(request):
    return render(request,'home/index.html')

kelompok13/funeducare/payments/views.py
from django.shortcuts import render

# Create your views here.

kelompok13/funeducare/profil/views.py
from django.shortcuts import render

# Create your views here.

kelompok13/funeducare/programs/views.py
from django.shortcuts import render

# Create your views here.

#? Membuat class form
from django import forms

""" Perlu di garis bawahi kalau untuk buat kelas form itu sama kayak models """
class ProgramsCompetitionForm(forms.Form):
  child_name = forms.CharField()
  parent_name = forms.CharField()
  parent_email = forms.EmailField()
  parent_phone = forms.CharField()


def programs(request):
  competition_form = ProgramsCompetitionForm()
  context = {
    'Judul': 'Our Programs',
    'competition_form': competition_form,
  }
  if request.method == "POST":
    print('ini POST')
    print(request.POST['child_name'])
    print(request.POST['parent_name'])
    print(request.POST['parent_email'])
    print(request.POST['parent_phone'])
  else:
    print('ini GET')
  return render(request, 'programs/programs.html', context)

kelompok13/funeducare/reports/views.py
from django.shortcuts import render

# Create your views here.

kelompok13/funeducare/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login,logout
from .forms import SignupForm
from .forms import LoginForm
from django.contrib.auth.decorators import login_required

@login_required
def user_logout(request):
    logout(request)
    next_url = request.GET.get('next', '/')  # Jika ada next di URL, arahkan ke halaman tersebut
    return redirect(next_url)  

def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Pendaftaran berhasil!')
            return redirect('users:login')
        else:
            messages.error(request, 'Ada kesalahan saat pengisian form.')
    else:
        form = SignupForm()
    
    return render(request, 'signup.html', {'form': form})

def user_login(request):
    form = LoginForm()  
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid(): 
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, 'Login berhasil! Selamat datang di FunEduCare.')
                    return redirect('home:home')  
                else:
                    messages.error(request, 'Akun Anda tidak aktif. Silakan hubungi admin.')
                    return redirect('users:login')
            else:
                messages.error(request, 'Username atau password salah.')
    return render(request, 'login.html', {'form': form})
    
def profile_view(request):
    return render(request, 'profile.html')

kelompok13/funeducare/payments/templates/pembayaran.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pembayaran</title>
    <link rel="stylesheet" href="{% static 'css/pembayaran-style.css' %}" />
  </head>
  <body>
    <div class="container">
      <aside class="sidebar">
        <div class="logo">
          <h3>FunEduCare</h3>
        </div>
        <ul class="menu">
          <li><a href="dashboard.html">Profil Anak</a></li>
          <li><a href="programaktif.html">Program Aktif</a></li>
          <li><a href="riwayatkegiatan.html">Riwayat Kegiatan</a></li>
          <li><a href="laporanperkembangan.html">Laporan Perkembangan</a></li>
          <li><a href="#">Pembayaran</a></li>
          <!-- Halaman saat ini -->
          <li><a href="pengaturanakun.html">Pengaturan Akun</a></li>
        </ul>
        <button class="btn-back" onclick="window.location.href='dashboard.html'">
          Kembali ke halaman utama
        </button>
      </aside>

      <main class="content">
        <h1>Pembayaran</h1>
        <h2>Tagihan Aktif</h2>

        <div class="billing-cards">
          <!-- Tagihan 1 -->
          <div class="billing-card">
            <h3>Infant Care- Bulan Oktober</h3>
            <p><strong>Total:</strong> Rp 2.000.000</p>
            <p><strong>Batas Pembayaran:</strong> 25 Oktober 2024</p>
            <button>Bayar Sekarang</button>
          </div>

          <!-- Tagihan 2 -->
          <div class="billing-card">
            <h3>Toddler Program - Bulan Oktober</h3>
            <p><strong>Total:</strong> Rp 1.800.000</p>
            <p><strong>Batas Pembayaran:</strong> 25 Oktober 2024</p>
            <button>Bayar Sekarang</button>
          </div>
          <!-- Tagihan 3 -->
          <div class="billing-card">
            <h3>Pre School- Bulan Oktober</h3>
            <p><strong>Total:</strong> Rp 1.600.000</p>
            <p><strong>Batas Pembayaran:</strong> 25 Oktober 2024</p>
            <button>Bayar Sekarang</button>
          </div>
          <!-- Tagihan 4 -->
          <div class="billing-card">
            <h3>Pre-kingdergarten - Bulan Oktober</h3>
            <p><strong>Total:</strong> Rp 1.500.000</p>
            <p><strong>Batas Pembayaran:</strong> 25 Oktober 2024</p>
            <button>Bayar Sekarang</button>
          </div>
        </div>

        <h2>Riwayat Pembayaran</h2>

        <div class="payment-history">
          <table>
            <thead>
              <tr>
                <th>Program</th>
                <th>Tanggal Pembayaran</th>
                <th>Total</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Infant Care- Bulan September</td>
                <td>28 September 2024</td>
                <td>Rp 2.000.000</td>
                <td>Lunas</td>
              </tr>
              <tr>
                <td>Toddler Program - Bulan September</td>
                <td>28September 2024</td>
                <td>Rp 1.800.000</td>
                <td>Lunas</td>
              </tr>
              <tr>
                <td>Pre School - Bulan September</td>
                <td>28 September 2024</td>
                <td>Rp 1.700.000</td>
                <td>Lunas</td>
              </tr>
              <tr>
                <td>Pre Pre-kingdergarten - Bulan September</td>
                <td>28September 2024</td>
                <td>Rp 1.500.000</td>
                <td>Lunas</td>
              </tr>
            </tbody>
          </table>
        </div>
      </main>
    </div>
  </body>
</html>

kelompok13/funeducare/profil/templates/invoice.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>invoice</title>
    <link rel="stylesheet" href="" />

    <link
      <link rel="stylesheet" href="{% static 'css/bigdata-style.css' %}" />
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />
    <!-- css -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <!-- link icon bostrap -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.0/font/bootstrap-icons.min.css"
    />
  </head>
  <body>
    <main>
      <section class="container">
        <div class="col-12 text-center p-5">
          <h1>invoice</h1>
        </div>
      </section>
    </main>
  </body>
</html>

kelompok13/funeducare/users/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet" />
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
  <link rel="stylesheet" href="{% static 'css/style_log-in_&_sign-up.css' %}" />
  <title>Log-in</title>
</head>

<body>
  
</div>
  <div class="home">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
</svg>
    <a href="{% url 'home:home' %}" class="link">Back Home</a>
  </div>
  {% if messages %}
                  <div class="alert-container">
                      {% for message in messages %}
                          <div class="alert alert-{{ message.tags }} alert-dismissible alert-succes fade show" role="alert">
                              {{ message }}
                              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                          </div>
                      {% endfor %}
                  </div>
    {% endif %}

</div>
  <div class="content col-md-auto">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-auto">
          <div class="picture">
            <img src="{% static 'images/img.png' %}" class="img-fluid img" alt="...">
          </div>
        </div>
        <div class="col-md-auto">
          <div class="form">
            <div class="box p-3">
              <h1 class="animate__animated animate__fadeInUp">Selamat Datang di FunEduCare!</h1>
              <p>
                Masuk untuk memantau perkembangan dan aktivitas belajar si
                kecil.
              </p>
            </div>
            <form method="POST">
              {% csrf_token %}
              <div class="mb-3">
                {{ form.username.label_tag }}
                {{ form.username }}
              </div>
          
              <div class="mb-3">
                {{ form.password.label_tag }}
                {{ form.password }}
              </div>
              <a href="forgot.html" class="link text-end " style="font-size: 15px; ">Forgot Password?</a>
              <button type="submit" class="btn btn-primary mt-2">Login</button>
          </form>
          
          
            <div class="submit-2">
              <button href="#" type="submit" class="btn-gg">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-google"
                  viewBox="0 0 16 16">
                  <path
                    d="M15.545 6.558a9.4 9.4 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.7 7.7 0 0 1 5.352 2.082l-2.284 2.284A4.35 4.35 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.8 4.8 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.7 3.7 0 0 0 1.599-2.431H8v-3.08z" />
                </svg>
                Sign in with Google
              </button>
              <p style="padding-top: 10px; font-size:15px" >
                Belum punya akun?
                <a class="link" href="{% url 'users:signup' %}">Sign Up</a>
              </p>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>

    <!-- Modal Pop-up -->
    {% comment %} <div id="loginSuccessModal" class="modal">
      <div class="modal-content">
        <p>Log-in Berhasil!</p>
        <img class="verified" src="./assets/images/verified.png" alt="Verified" />
        <div class="modal-body">
          Selamat, Anda telah berhasil masuk ke FunEduCare
          <button class="btn-modal close-btn">OK</button>
        </div>
      </div>
    </div> {% endcomment %}

    <!-- Menampilkan Pesan Sukses atau Error -->
   
    <script src="{% static 'js/log-in.js' %}"></script>
</body>

</html>

kelompok13/funeducare/users/templates/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Profile</title>

    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

    <!-- Bootstrap JS Bundle (includes Popper.js) -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <!-- Sidebar for mobile with offcanvas -->
        <div class="col-12">
          <!-- Button to open offcanvas menu -->
          <button
            class="btn btn-primary mt-3 ms-3"
            type="button"
            data-bs-toggle="offcanvas"
            data-bs-target="#offcanvasSidebar"
            aria-controls="offcanvasSidebar"
          >
            Menu Profil
          </button>

          <!-- Offcanvas Sidebar -->
          <div
            class="offcanvas offcanvas-start"
            tabindex="-1"
            id="offcanvasSidebar"
            aria-labelledby="offcanvasSidebarLabel"
          >
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasSidebarLabel">
                Profil Anda
              </h5>
              <button
                type="button"
                class="btn-close"
                data-bs-dismiss="offcanvas"
                aria-label="Close"
              ></button>
            </div>
            <div class="offcanvas-body">
              <div class="text-center mb-4">
                <img
                  src="{% static 'images/h-4-m2.jpg' %}"
                  alt="logo"
                  width="150"
                  height="150"
                  class="rounded-circle mb-2"
                />
                <h3>Susilo</h3>
              </div>
              <ul class="nav flex-column gap-2">
                <li class="nav-item">
                  <a class="nav-link" href="#" aria-current="page">
                    <i class="fas fa-user me-2 fa-2x"></i> Profil Anak
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <i class="fas fa-book me-2 fa-2x"></i> Program Aktif
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <i class="fas fa-layer-group me-2 fa-2x"></i> Riwayat
                    Kegiatan
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <i class="fas fa-folder me-2 fa-2x"></i> Laporan
                    Perkembangan
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <i class="fas fa-money-check me-2 fa-2x"></i> Pembayaran
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <i class="fas fa-gear me-2 fa-2x"></i> Pengaturan Akun
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <!-- Sidebar for desktop -->
        <aside
          class="col-md-3 col-lg-3 d-none d-md-block bg-light vh-100 p-5"
          style="
            box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.3);
            position: fixed;
            width: 350px;
          "
        >
          <div class="text-center mb-2">
            <img
              src="{% static 'images/h-4-m2.jpg' %}"
              alt="logo"
              width="150"
              height="150"
              class="rounded-circle"
            />
            <h3>Susilo</h3>
          </div>
          <ul class="navbar-nav flex-column gap-2">
            <li class="nav-item">
              <a class="nav-link" href="#" aria-current="page">
                <i class="fas fa-user me-2 fa-1x"></i> Profil
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="fas fa-book me-2 fa-1x"></i> Program Aktif
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="fas fa-layer-group me-2 fa-1x"></i> Riwayat Kegiatan
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="fas fa-folder me-2 fa-1x"></i> Laporan Perkembangan
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="fas fa-money-check me-2 fa-1x"></i> Pembayaran
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="fas fa-gear me-2 fa-1x"></i> Pengaturan Akun
              </a>
            </li>

            <a class="btn btn-secondary" href="{% url 'home:home' %}"
              >Back to home</a
            >
            <form action="{% url 'users:logout' %}" method="post">
              {% csrf_token %}
              <button
                type="submit"
                class="nav-link text-dark"
                style="font-size: 25px; font-weight: 600"
              >
                Logout
              </button>
            </form>
          </ul>
        </aside>
        <!-- Main Content -->
        <div class="col-12 col-md-9 ms-md-auto mt-4 text-center">
          <h1>Profil</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsa
            dignissimos rem vel dolore, amet, ipsam nemo possimus illum.
          </p>
        </div>
      </div>
    </div>

    <!-- Bootstrap Bundle JS (this already includes Popper.js) -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

kelompok13/funeducare/users/templates/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      href="https://getbootstrap.com/docs/5.3/assets/css/docs.css"
      rel="stylesheet"
    />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap"
      rel="stylesheet"
    />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/style_log-in_&_sign-up.css' %}"
    />
    <title>Sign-Up</title>
  </head>

  <body>
    <div class="home">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        fill="currentColor"
        class="bi bi-arrow-left"
        viewBox="0 0 16 16"
      >
        <path
          fill-rule="evenodd"
          d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"
        />
      </svg>
      <a href="{% url 'users:login' %}" class="link">Back Log-In</a>
    </div>
    <div class="container mt-2">
      {% if messages %}
          <div class="alert-container ">
              {% for message in messages %}
                  <div class="alert alert-{{ message.tags }} alert-dismissible alert-danger a fade show" role="alert">
                      {{ message }}
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
              {% endfor %}
          </div>
      {% endif %}
  
  </div>
    <div class="content">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-auto">
            <div class="picture ">
              <img
                src="{% static 'images/img.png' %}"
                class="img-fluid img"
                alt="..."
              />
            </div>
          </div>
          <div class="col-md-auto">
            <div class="form" style="margin-top:-30px;">
              <form
                action="{% url 'users:signup' %}"
                id="signinForm"
                method="post"           
              >
                {% csrf_token %}
                <div class="box">
                  <h1 class="animate__animated animate__fadeInUp">
                   Daftarkan akun Anda!
                  </h1>             
                </div>
                <div class="mb-2">
                  <label for="username" class="form-label">Username</label>
                  {{ form.username }}
                </div>
                <div class="mb-2">
                  <label for="email" class="form-label">Email</label>
                  {{ form.email }}
                </div>
                <div class="">                
                  <label for="password" class="form-label">Password</label>
                  <p style="font-size:15px" class="text-danger">Password Minimal 8 karakter!</p>
                  {{ form.password1 }}
                </div>
                <div class="mb-2">
                  <label for="password" class="form-label"
                    >Verifikasi Password</label
                  >
                  {{ form.password2 }}
                </div>
                <div class="submit">
                  <button href="./login.html" type="submit" class="btn">
                    Sign Up
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal Pop-up -->
    {% comment %} <div id="loginSuccessModal" class="modal">
      <div class="modal-content">
        <p id="signupSuccessLabel">Sign-Up Berhasil!</p>
        <img
          class="verified"
          src="./assets/images/verified.png"
          alt="Verified"
        />
        <div class="modal-body">
          Selamat, Anda telah berhasil gabung ke FunEduCare
          <button class="btn-modal close-btn">OK</button>
        </div>
      </div> {% endcomment %}
    </div>
   
    </script>
    <!-- Include jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static ' js/sign-up.js ' %}"></script>
  </body>
</html>