kelompok13/funeducare/aboutus/urls.py
from django.urls import path
from . import views

app_name = 'aboutus'
urlpatterns = [
    path('', views.aboutus_view, name='aboutus'),  
]

kelompok13/funeducare/contactus/urls.py
from django.urls import path
from . import views


app_name='contactus'

urlpatterns = [
    path('', views.contactus_view, name='contactus'),
]

kelompok13/funeducare/funeducare/urls.py
from django.contrib import admin
from django.urls import path, include
from aboutus import views
from contactus import views
from home import views
from payments import views
from pendaftaran import views
from profil import views
from programs import views
from users import views

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('contactus/', include('contactus.urls')),
    path('aboutus/', include('aboutus.urls')),
    path('programs/', include('programs.urls')),
    path('users/', include('users.urls')),
    
]

kelompok13/funeducare/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home_view, name='home'),
]

kelompok13/funeducare/payments/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

kelompok13/funeducare/pendaftaran/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

kelompok13/funeducare/profil/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

kelompok13/funeducare/programs/urls.py
from django.urls import path
from . import views

app_name = 'programs'

urlpatterns = [
    path('', views.programs, name='programs'),
]

kelompok13/funeducare/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
app_name = 'users'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.user_logout, name='logout'),
    path('login/', views.user_login, name='login'),
    path('profile/', views.profile_view, name='profile'),
    
]

kelompok13/funeducare/profil/models.py
from django.db import models

# Create your models here.

kelompok13/funeducare/reports/models.py
from django.db import models

# Create your models here.

kelompok13/funeducare/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):


    def __str__(self):
        return self.username

kelompok13/funeducare/contactus/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100, required=True)
    email = forms.EmailField(label='Email', required=True)
    contact = forms.CharField(label='Contact Number', max_length=20, required=True)
    message = forms.CharField(label='Message', widget=forms.Textarea, required=True)

kelompok13/funeducare/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class SignupForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Masukkan Email Anda'})
    )
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Masukkan Password Anda'})
    )
    password2 = forms.CharField(
        label="Verifikasi Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Masukkan Ulang Password Anda'})
    )

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Masukkan Username Anda'}),
        }
        
class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

kelompok13/funeducare/aboutus/views.py
from django.shortcuts import render

# Create your views here.
def aboutus_view(request):
    return render(request, 'aboutus/aboutus.html')

kelompok13/funeducare/contactus/views.py
from django.shortcuts import render

# Create your views here.
def contactus_view(request):
    return render(request,'contactus/contactus.html')

kelompok13/funeducare/home/views.py
from django.shortcuts import render

# Create your views here.
def home_view(request):
    return render(request,'home/index.html')

kelompok13/funeducare/payments/views.py
from django.shortcuts import render

# Create your views here.

kelompok13/funeducare/profil/views.py
from django.shortcuts import render

# Create your views here.

kelompok13/funeducare/programs/views.py
from django.shortcuts import render

# Create your views here.

#? Membuat class form
from django import forms

""" Perlu di garis bawahi kalau untuk buat kelas form itu sama kayak models """
class ProgramsCompetitionForm(forms.Form):
  child_name = forms.CharField()
  parent_name = forms.CharField()
  parent_email = forms.EmailField()
  parent_phone = forms.CharField()


def programs(request):
  competition_form = ProgramsCompetitionForm()
  context = {
    'Judul': 'Our Programs',
    'competition_form': competition_form,
  }
  if request.method == "POST":
    print('ini POST')
    print(request.POST['child_name'])
    print(request.POST['parent_name'])
    print(request.POST['parent_email'])
    print(request.POST['parent_phone'])
  else:
    print('ini GET')
  return render(request, 'programs/programs.html', context)

kelompok13/funeducare/reports/views.py
from django.shortcuts import render

# Create your views here.

kelompok13/funeducare/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login,logout
from .forms import SignupForm
from .forms import LoginForm
from django.contrib.auth.decorators import login_required

@login_required
def user_logout(request):
    logout(request)
    next_url = request.GET.get('next', '/')  # Jika ada next di URL, arahkan ke halaman tersebut
    return redirect(next_url)  

def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Pendaftaran berhasil!')
            return redirect('users:login')
        else:
            messages.error(request, 'Ada kesalahan saat pengisian form.')
    else:
        form = SignupForm()
    
    return render(request, 'signup.html', {'form': form})

def user_login(request):
    form = LoginForm()  
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid(): 
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, 'Login berhasil! Selamat datang di FunEduCare.')
                    return redirect('home:home')  
                else:
                    messages.error(request, 'Akun Anda tidak aktif. Silakan hubungi admin.')
                    return redirect('users:login')
            else:
                messages.error(request, 'Username atau password salah.')
    return render(request, 'login.html', {'form': form})
    
def profile_view(request):
    return render(request, 'profile.html')

kelompok13/funeducare/templates/base/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{% block head_title %} {{Judul}} {% endblock head_title %}</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/home-style.css' %}" />
    {% block extra_css %}{% endblock %}
    <!-- css -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.0/font/bootstrap-icons.min.css"
    />
  </head>
  <body>
    <!-- navbar -->
    <header>
      <nav class="navbar navbar-expand-lg fixed-top">
        <div
          class="container-fluid me-3 ms-3 rounded-5"
          style="background-color: #cfcfcf"
        >
          <a class="navbar-brand me-auto p-3" href="#">
            <img
              src="{% static 'images/logo2.png' %}"
              alt="logo"
              width="40px"
            />
          </a>
          <div
            class="offcanvas offcanvas-end text-center"
            tabindex="-1"
            id="offcanvasNavbar"
            aria-labelledby="offcanvasNavbarLabel"
            style="background-color: #cfcfcf"
          >
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
                <img
                  src="{% static 'images/logo2.png' %}"
                  alt="logo"
                  class="logo-small"
                />
              </h5>
              <button
                type="button"
                class="btn-close bg-light"
                data-bs-dismiss="offcanvas"
                aria-label="Close"
              ></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-center flex-grow-1 pe-4">
                <li class="nav-item">
                  <a
                    class="nav-link mx-lg-3"
                    aria-current="page"
                    href="{% url 'home:home' %}"
                    >HOME</a
                  >
                </li>
                <li class="nav-item">
                  <a class="nav-link mx-lg-3" href="{% url 'aboutus:aboutus' %}"
                    >ABOUT US</a
                  >
                </li>
                <li class="nav-item">
                  <a
                    class="nav-link mx-lg-3"
                    href="{% url 'programs:programs' %}"
                    >PROGRAMS</a
                  >
                </li>

                <li class="nav-item">
                  <a
                    class="nav-link mx-lg-3"
                    href="{% url 'contactus:contactus' %}"
                    >CONTACT-US</a
                  >
                </li>
              </ul>
            </div>
          </div>
          <div class="d-flex align-items-center" id="loginForm">
            {% if user.is_authenticated %}
            <a href="{% url 'users:profile' %}" class="p-2 me-2">
              <img
                src="{% static 'images/IMG_6643.png' %}"
                alt="Profile"
                class="profile-icon rounded-circle bg-dark"
                width="35px"
                height="35px"
              />
            </a>
            {% else %}
            <a href="{% url 'users:login' %}" class="signup-button p-2 me-2"
              >Open Your Account</a
            >
            {% endif %}
            <button
              class="navbar-toggler pe-2"
              type="button"
              data-bs-toggle="offcanvas"
              data-bs-target="#offcanvasNavbar"
              aria-controls="offcanvasNavbar"
              aria-label="Toggle navigation"
            >
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
        </div>
      </nav>
    </header>

    {% comment %} content {% endcomment %}
    <body>
      {% block body_block %} {% endblock %}
    </body>
    {% comment %} content {% endcomment %}
    <footer class="container-footer footer">
      <div class="pt-4 p-5">
        <div class="row">
          <div class="col-md-4">
            <ul class="list1">
              <li>
                <a href="{% url 'aboutus:aboutus' %}#siapakami">Tentang Kami</a>
              </li>
              <li><a href="{% url 'programs:programs' %}">Pendaftaran</a></li>
              <li>
                <a href="{% url 'home:home' %}#testimonialCarousel"
                  >Testimoni</a
                >
              </li>
              <li><a href="{% url 'contactus:contactus' %}#faqq">FAQ</a></li>
              <li>
                <a href="{% url 'contactus:contactus' %}#konsultasi"
                  >Konsultasi</a
                >
              </li>
              <li><a href="{% url 'home:home' %}#fasilitas">Fasilitas</a></li>
              <li><a href="{% url 'aboutus:aboutus' %}#galeri">Galeri</a></li>
            </ul>
          </div>
          <!-- footer column 2 -->
          <div class="col-md-4">
            <h4>Paket Kami</h4>
            <ul class="list2">
              <li>
                <a href="{% url 'programs:programs' %}#service">Infant Care</a>
              </li>
              <li>
                <a href="{% url 'programs:programs' %}#service"
                  >Toddler Program</a
                >
              </li>
              <li>
                <a href="{% url 'programs:programs' %}#service"
                  >Pre-School Program</a
                >
              </li>
              <li>
                <a href="{% url 'programs:programs' %}#service"
                  >Pre-Kindergarten</a
                >
              </li>
              <li>
                <a href="{% url 'programs:programs' %}#service"
                  >Upcoming Events</a
                >
              </li>
              <li>
                <a href="{% url 'programs:programs' %}#service"
                  >Program Lainnya</a
                >
              </li>
            </ul>
          </div>

          <div class="col-md-4">
            <h4>Kontak Kami</h4>
            <ul class="list4">
              <li>
                <i class="bi bi-geo-alt me-2"></i>
                Jl.Mawar No 123, Jakarta, Indonesia
              </li>
              <br />
              <li>
                <i class="bi bi-whatsapp me-2"></i>
                088221319983
              </li>
              <br />
              <li>
                <i class="bi bi-envelope me-2"></i>
                funeducare@gmail.com
              </li>
            </ul>
          </div>
          <!-- btn up -->
          {% comment %}
          <div class="button-group d-flex justify-content-center mb-4">
            <button id="backToTop" class="btn btn-1">Back to Top</button>
          </div>
          {% endcomment %}
          <!-- footer column 3/social media -->
          <div class="d-flex justify-content-center mt-5">
            <div class="col-md-4 text-center">
              <h5 class="follow">Follow Us</h5>
              <a
                href="https://www.facebook.com/ruanggurucom/"
                class="text-white me-2"
                ><i class="bi bi-facebook"></i
              ></a>
              <a href="https://x.com/ruangguru/" class="text-white me-2"
                ><i class="bi bi-twitter"></i
              ></a>
              <a
                href="https://www.instagram.com/ruangguru/"
                class="text-white me-2"
                ><i class="bi bi-instagram"></i
              ></a>
              <a
                href="https://www.linkedin.com/company/ruangguru-com?referralCookiesId=23cf3dc9-bba5-43d3-ba10-a086684aef0e"
                class="text-white me-2"
                ><i class="bi bi-linkedin"></i
              ></a>
            </div>
          </div>
        </div>
        <!-- Footer Bottom -->
        <div class="copyright text-center mt-4">
          <p>Copyright &copy; 2024 FunEduCare. All rights reserved.</p>
        </div>
      </div>
    </footer>

    <script src="" async defer></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- link js-bootstrap -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/home.js' %}"></script>
  </body>
</html>